/**
 * Plugin Registry - Dynamic Component Loading
 * 
 * This file maps plugin keys to their React components.
 * It is auto-generated by scanning the plugins directory.
 * 
 * Run: npm run generate:plugins
 */

import dynamic from 'next/dynamic';
import { ComponentType } from 'react';

// Plugin component props interface
export interface PluginViewProps {
  pluginKey: string;
  pluginData?: any;
}

// Loading component for dynamic imports
const LoadingComponent = () => (
  <div className="flex items-center justify-center py-12">
    <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600"></div>
  </div>
);

// Error component when plugin not found
const NotFoundComponent = ({ pluginKey }: { pluginKey: string }) => (
  <div className="text-center py-12">
    <div className="text-4xl mb-4">🔌</div>
    <h2 className="text-xl font-semibold text-gray-900">Plugin non trouvé</h2>
    <p className="text-gray-500 mt-2">
      Aucun composant frontend pour le plugin &quot;{pluginKey}&quot;
    </p>
  </div>
);

// Registry of plugin components
// Each plugin can register its main view component here
const pluginComponents: Record<string, ComponentType<PluginViewProps>> = {
  // Built-in plugins with custom views
  wifi: dynamic(() => import('@/components/plugins/WiFiPentestView').then(m => ({ default: m.WiFiPentestView })), {
    loading: LoadingComponent,
  }),
  
  healthcheck: dynamic(() => import('@/components/plugins/HealthcheckView').then(m => ({ default: m.HealthcheckView })), {
    loading: LoadingComponent,
  }),
  
  // Add more plugins here or they will use the dynamic schema renderer
};

/**
 * Get the component for a plugin
 * Returns the custom component if registered, otherwise null (will use DynamicRenderer)
 */
export function getPluginComponent(pluginKey: string): ComponentType<PluginViewProps> | null {
  const normalized = pluginKey.toLowerCase();
  return pluginComponents[normalized] || null;
}

/**
 * Check if a plugin has a custom component
 */
export function hasCustomComponent(pluginKey: string): boolean {
  return pluginKey.toLowerCase() in pluginComponents;
}

/**
 * Register a plugin component dynamically
 * This can be called by external plugins to register their components
 */
export function registerPluginComponent(
  pluginKey: string, 
  component: ComponentType<PluginViewProps>
): void {
  pluginComponents[pluginKey.toLowerCase()] = component;
}

/**
 * Get all registered plugin keys
 */
export function getRegisteredPlugins(): string[] {
  return Object.keys(pluginComponents);
}

// Export the NotFound component for use in plugin pages
export { NotFoundComponent };
